import { Phase, Roster, Strat } from './types'

export const PHASES: Phase[] = [
  { id: 'command',     n: 1, abbr: 'CMD', name: 'Command' },
  { id: 'movement',    n: 2, abbr: 'MOV', name: 'Movement' },
  { id: 'shooting',    n: 3, abbr: 'SHO', name: 'Shooting' },
  { id: 'charge',      n: 4, abbr: 'CHG', name: 'Charge' },
  { id: 'fight',       n: 5, abbr: 'FGT', name: 'Fight' },
  { id: 'battleshock', n: 6, abbr: 'BSK', name: 'Battleshock' },
]

export const SAMPLE_ROSTER: Roster = {
  fight: [
    {
      id: 'assault-vets',
      name: 'Assault Veterans',
      role: 'Assault Infantry',
      models: 5,
      tags: ['MELEE', 'AURA'],
      hot: ['+1 Atk if charged'],
      enhancements: [],
      weapons: [
        {
          name: 'Power Blades',
          kind: 'melee',
          stats: { A: '4', WS: '3+', S: '5', AP: '-2', D: '1' },
          tags: ['Melee', 'Extra Attacks'],
          mods: [
            { label: '+1 Attack', cond: 'if charged' },
            { label: 'Reroll Wounds', cond: 'from Leader' },
          ],
        },
        {
          name: 'Twin Sidearm',
          kind: 'melee',
          stats: { A: '3', WS: '3+', S: '4', AP: '0', D: '1' },
          tags: ['Melee'],
          mods: [],
        },
      ],
      abilities: [
        {
          name: 'Momentum Strike',
          timing: 'Fight phase',
          cond: 'If this unit charged',
          effect: 'Improve melee output this activation.',
          source: 'Unit Ability',
          category: 'datasheet',
        },
        {
          name: 'Sworn Vow',
          timing: 'Activation',
          cond: 'Leader attached',
          effect: 'Reroll wound rolls of 1 against the chosen target.',
          source: 'Faction Rule',
          category: 'datasheet',
        },
      ],
      stratagems: [
        {
          name: 'Counter-Offensive Drill',
          cp: 2,
          timing: 'After enemy unit fights',
          cond: 'Eligible unit',
          effect: 'Selected unit fights immediately.',
          source: 'Detachment',
          once: false,
        },
        {
          name: 'Final Stand',
          cp: 1,
          timing: 'Fight phase',
          cond: 'Below half-strength',
          effect: 'Lethal Hits on melee attacks this phase.',
          source: 'Core',
          once: 'battle',
        },
      ],
      reminders: [
        { text: 'Resolve activations alternating with opponent.' },
      ],
    },
    {
      id: 'ironclad',
      name: 'Ironclad Walker',
      role: 'Heavy Walker',
      models: 1,
      tags: ['MELEE', 'VEHICLE'],
      hot: ['Devastating Wounds'],
      enhancements: [],
      weapons: [
        {
          name: 'Demolisher Fist',
          kind: 'melee',
          stats: { A: '5', WS: '3+', S: '12', AP: '-3', D: 'D6' },
          tags: ['Melee', 'Devastating Wounds'],
          mods: [
            { label: '+1 to Wound', cond: 'vs Monster/Vehicle' },
          ],
        },
        {
          name: 'Crushing Tread',
          kind: 'melee',
          stats: { A: '3', WS: '4+', S: '7', AP: '-1', D: '2' },
          tags: ['Melee'],
          mods: [],
        },
      ],
      abilities: [
        {
          name: 'Cogwork Endurance',
          timing: 'Any phase',
          cond: 'Always on',
          effect: 'Halve incoming damage from melee attacks (round up).',
          source: 'Unit Ability',
          category: 'datasheet',
        },
      ],
      stratagems: [
        {
          name: 'Override Protocol',
          cp: 1,
          timing: 'Fight phase',
          cond: 'Targeting Vehicle',
          effect: 'Sustained Hits 2 on melee attacks this phase.',
          source: 'Detachment',
          once: 'phase',
        },
      ],
      reminders: [],
    },
    {
      id: 'battle-priest',
      name: 'Battle Priest',
      role: 'Character · Leader',
      models: 1,
      tags: ['MELEE', 'LEADER'],
      hot: ['+1 Atk aura'],
      enhancements: [],
      weapons: [
        {
          name: 'Reliquary Maul',
          kind: 'melee',
          stats: { A: '4', WS: '2+', S: '6', AP: '-2', D: '2' },
          tags: ['Melee', 'Precision'],
          mods: [],
        },
      ],
      abilities: [
        {
          name: 'Litany of the First Strike',
          timing: 'Fight phase',
          cond: 'Aura · attached unit',
          effect: '+1 Attack to melee weapons.',
          source: 'Unit Ability',
          category: 'datasheet',
        },
      ],
      stratagems: [],
      reminders: [
        { text: 'Aura applies before resolving any attacks this phase.' },
      ],
    },
  ],
  shooting: [
    {
      id: 'fireline-squad',
      name: 'Fireline Squad',
      role: 'Line Infantry',
      models: 10,
      tags: ['RANGED', 'HAZARDOUS'],
      hot: ['+1 Hit if stationary'],
      enhancements: [],
      weapons: [
        {
          name: 'Plasma Rifle',
          kind: 'ranged',
          stats: { R: '24"', A: '2', BS: '3+', S: '8', AP: '-3', D: '2' },
          tags: ['Hazardous', 'Rapid Fire'],
          mods: [{ label: '+1 to Hit', cond: 'if remained stationary' }],
        },
        {
          name: 'Pulse Carbine ×8',
          kind: 'ranged',
          stats: { R: '18"', A: '2', BS: '4+', S: '4', AP: '0', D: '1' },
          tags: ['Assault'],
          mods: [],
        },
        {
          name: 'Heavy Lance',
          kind: 'ranged',
          stats: { R: '36"', A: '1', BS: '4+', S: '9', AP: '-3', D: 'D3+3' },
          tags: ['Heavy', 'Anti-Vehicle 4+'],
          mods: [{ label: 'Lethal Hits', cond: 'vs Vehicle' }],
        },
      ],
      abilities: [
        {
          name: 'Mark Target',
          timing: 'Shooting phase',
          cond: 'Once per phase',
          effect: 'Selected enemy unit suffers -1 to its next save.',
          source: 'Unit Ability',
          category: 'datasheet',
        },
      ],
      stratagems: [
        {
          name: 'Calibrated Volley',
          cp: 1,
          timing: 'Shooting phase',
          cond: 'Unit did not move',
          effect: 'Sustained Hits 1 on ranged attacks this phase.',
          source: 'Detachment',
          once: false,
        },
      ],
      reminders: [
        { text: 'Hazardous: roll 1 → model destroyed after shooting.' },
      ],
    },
    {
      id: 'recon-drone',
      name: 'Recon Drone',
      role: 'Light Skimmer',
      models: 2,
      tags: ['RANGED', 'FAST'],
      hot: [],
      enhancements: [],
      weapons: [
        {
          name: 'Burst Cannon',
          kind: 'ranged',
          stats: { R: '18"', A: '4', BS: '4+', S: '5', AP: '0', D: '1' },
          tags: ['Assault'],
          mods: [],
        },
      ],
      abilities: [
        {
          name: 'Spotter Array',
          timing: 'Shooting phase',
          cond: 'Visible target',
          effect: 'Friendly units ignore cover against the chosen target.',
          source: 'Unit Ability',
          category: 'datasheet',
        },
      ],
      stratagems: [],
      reminders: [],
    },
  ],
}

export const SAMPLE_STRATAGEMS: Strat[] = [
  {
    name: 'Counter-Offensive',
    cp: 2,
    timing: 'Fight phase',
    effect: 'WHEN: In the Fight phase, after an enemy unit has fought.\nEFFECT: Select one unit from your army that is within Engagement Range of one or more enemy units and that has not already been selected to fight this phase. That unit fights next.',
    summary: 'Your unit fights immediately after an enemy unit, jumping the queue.',
    source: 'Core',
    once: false,
  },
  {
    name: 'Rapid Ingress',
    cp: 1,
    timing: 'Movement phase',
    effect: 'WHEN: In your opponent\'s Movement phase, after your opponent has finished all moves.\nEFFECT: Select one unit from your army that is in Reserves. That unit can arrive on the battlefield as if it were the Reinforcements step of your Movement phase.',
    summary: 'Deploy a Reserves unit at the end of your opponent\'s Movement phase.',
    source: 'Core',
    once: false,
  },
  {
    name: 'Smokescreen',
    cp: 1,
    timing: 'Movement phase',
    effect: 'WHEN: In any phase, just after an enemy unit has selected its targets.\nEFFECT: Select one SMOKE unit from your army that was selected as a target. Until the end of the phase, all models in that unit have the Benefit of Cover, and the Stealth ability.',
    summary: 'Give a Smoke unit cover saves and Stealth against the current attacker.',
    source: 'Core',
    once: false,
  },
  {
    name: 'Command Re-roll',
    cp: 1,
    timing: 'Command phase',
    effect: 'WHEN: In any phase, just after you have made a Hit roll, a Wound roll, a Damage roll, a saving throw, or an Advance roll for a model in your army.\nEFFECT: Re-roll that roll.',
    summary: 'Re-roll any single dice result immediately after rolling it.',
    source: 'Core',
    once: false,
  },
  {
    name: 'Insane Bravery',
    cp: 1,
    timing: 'Battleshock phase',
    effect: 'WHEN: In the Battleshock phase, just after a Battle-shock test has been failed for a unit from your army.\nEFFECT: That unit is no longer Battle-shocked.',
    summary: 'Instantly remove Battle-shocked status from a friendly unit.',
    source: 'Core',
    once: 'battle',
  },
]
